### ISSUE TITLE
confluence page text too dark

### ISSUE THREAD

**Issue by B4rryD4vis** [jbronssin/jira-black#14]
This used to be ok, but as there hasn't been much change to jira-black, I guess Atlassian have made a change that has caused the colours to change on confluence pages. This is with jira-black 0.3.
Disabled:
![image](https://user-images.githubusercontent.com/12561891/191305483-b36ab28e-ee9a-4fc8-b71b-6b0f27196ce1.png)
Enabled:
![image](https://user-images.githubusercontent.com/12561891/191304425-3c85b417-beb5-43c9-a12e-5d5c7def43af.png)

**Comment by PaulMEdwards** [comment]
I'm experiencing the same and came here to report this as an issue.

**Comment by jbronssin** [comment]
Hey guys!
Many thanks for your feedback :) 
I'm currently working on it, will keep you posted.

**Comment by Julian88Tex** [comment]
@jbronssin Same and looking forward to fix! At the very least a (hopefully) quick fix would be nice to have an option to exclude Confluence until this is improved. Might be a good option to have regardless. Thanks for creating this extension!

**Comment by Julian88Tex** [comment]
@jbronssin do you have steps for testing the branch you're working on locally? I haven't done that before for an extension but would love to give feedback on it.

**Comment by Rep0se** [comment]
Confluence-page-text-too-dark branch fixes the issue, and so far it looks good for Confluence. It does however break the color for Jira ticket body text.

**Comment by jbronssin** [comment]
yes indeed, it does breaks my mind... what works on one side breaks the other 🤯 .
I'm trying to find a way to make it work... Sorry guys!

**Comment by PaulMEdwards** [comment]
@jbronssin Perhaps it might be necessary to have 2 separate extensions? One for Jira, and one for Confluence.

**Comment by Julian88Tex** [comment]
@jbronssin any blocker to getting this PR created? https://github.com/jbronssin/jira-black/compare/jbronssin:main...jbronssin:Confluence-page-text-too-dark?expand=1

**Comment by Rep0se** [comment]
It's worth adding exception to manifest.json into "content_scripts" for the time being:
`"exclude_matches":["https://*.atlassian.net/wiki/*"],`

**Comment by jbronssin** [comment]
@Rep0se you are super right, I'll do it very soon. Sorry for the delay 🙏🏻

**Comment by dsbilling** [comment]
Any updates on this? My eyes are burning in Confluence 👓

**Comment by PaulMEdwards** [comment]
I switched to Dark Reader and haven't looked back. It works great everywhere.

**Comment by jbronssin** [comment]
I'm sorry guys! I've been a bit too busy lately, I'll try that today!
