### ISSUE TITLE
Unstyled checklist (in iframe)

### ISSUE THREAD

**Issue by fortunato** [jbronssin/jira-black#5]
Hi there,

Thanks for providing us with this extension. Me and my team started using it today but realized that the "Issue Checklist for Jira" app from herocoders loads in an iframe and was thus not enjoying the inverted styling.

Would you consider accepting a PR or implement support for this yourself?

(This relates to Eric Satterwhite his comment under the support tab on the chrome web store)

The patch would be as follows:
```diff
Index: manifest.json
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/manifest.json b/manifest.json
--- a/manifest.json	(revision 17afdcd103f40ea166865520fedbe150998dc881)
+++ b/manifest.json	(revision f3c42d5d1e0164a7e43419c056b006d3b85dbda4)
@@ -9,9 +9,10 @@
   },
   "content_scripts": [
     {
-      "matches": ["https://*.atlassian.net/*"],
+      "matches": ["https://*.atlassian.net/*", "https://*.herocoders.com/issue/*"],
       "js": ["script.js"],
-      "css": ["style.css"]
+      "css": ["style.css"],
+      "all_frames": true
     }
   ]
 }
\ No newline at end of file
```

**Comment by jbronssin** [comment]
Hey!

Many thanks for your contribution, unfortunately I don't use herocoders so I could not test it.
Your contribution could also be a direct PR, but I can do it right away.
I gave the code of this small extension just to make it more universal and to get good ideas from users like you ! \o/
Let me test it, and push it to Chrome Dev so that it will be updated tonight.
Keep an eye on the version on the store / extension manager : it'll be the `0.2.5`

**Comment by fortunato** [comment]
Legend, thanks!

**Comment by jbronssin** [comment]
It's live in the Chrome Store since this morning. Don't hesitate to tell me if it's not working !

**Comment by fortunato** [comment]
It's working :ok_hand:

**Comment by codeversed** [comment]
Same issue for Smart Checklists. The url that the Smart Checklists plugin uses is the following: `jirachecklist.com`.

Could you add a feature to allow adding our own filters?  Thanks!

**Comment by jbronssin** [comment]
@codeversed Interesting point, unfortunately, after the last modification I made with herocoders, the extension had a significant drop in usage as chrome will block it for 100% of the users. It'll come back if they agree on giving the new right to read another domain. "No big deal" in a way, but it's like a never-ending story as the amount of jira integrated extensions is gigantic. 
I would suggest to have this extension installed as a developper.
You can directly get this branch in which I made the very simple edit: https://github.com/jbronssin/jira-black/tree/Jirachecklist
